INSERT INTO ProductDetails([TypeGlass],[TypeBorder],[TypeMachine],[Origin],[Brand],[Warranty],[Parameter],[ResistWater],[Func],[Color],[Description]) VALUES(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
');
INSERT INTO ProductDetails([TypeGlass],[TypeBorder],[TypeMachine],[Origin],[Brand],[Warranty],[Parameter],[ResistWater],[Func],[Color],[Description]) VALUES(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
');
INSERT INTO ProductDetails([TypeGlass],[TypeBorder],[TypeMachine],[Origin],[Brand],[Warranty],[Parameter],[ResistWater],[Func],[Color],[Description]) VALUES(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
');
INSERT INTO ProductDetails([TypeGlass],[TypeBorder],[TypeMachine],[Origin],[Brand],[Warranty],[Parameter],[ResistWater],[Func],[Color],[Description]) VALUES(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
');
INSERT INTO ProductDetails([TypeGlass],[TypeBorder],[TypeMachine],[Origin],[Brand],[Warranty],[Parameter],[ResistWater],[Func],[Color],[Description]) VALUES(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
');
INSERT INTO ProductDetails([TypeGlass],[TypeBorder],[TypeMachine],[Origin],[Brand],[Warranty],[Parameter],[ResistWater],[Func],[Color],[Description]) VALUES(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
');
INSERT INTO ProductDetails([TypeGlass],[TypeBorder],[TypeMachine],[Origin],[Brand],[Warranty],[Parameter],[ResistWater],[Func],[Color],[Description]) VALUES(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
');
INSERT INTO ProductDetails([TypeGlass],[TypeBorder],[TypeMachine],[Origin],[Brand],[Warranty],[Parameter],[ResistWater],[Func],[Color],[Description]) VALUES(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
');
INSERT INTO ProductDetails([TypeGlass],[TypeBorder],[TypeMachine],[Origin],[Brand],[Warranty],[Parameter],[ResistWater],[Func],[Color],[Description]) VALUES(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thụy Sỹ',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Sivler',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Nhật',N'Casio',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
'),(N'Sapphire (Kính Chống Trầy)',N'Thép Không Gỉ',N'Automatic (Tự Động)',N'Thái Lan',N'Tissot',N'1 Năm',N'29mm x 20mm x 10mm
',N'3 ATM',N'Xem Giờ, Xem lịch',N'Gold',N'Đồng hồ/Timex là điểm nhấn sáng tạo của ngành công nghệ đồng hồ nước Mỹ. Nó đã ra đời và thực hiện tròn sứ mệnh của mình là trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.Cho dù là hàng trăm năm hay hàng nghìn năm, bằng những ưu điểm vượt trội này, nó sẽ “sống mãi” và trở thành tâm điểm trong ngành đồng hồ trang sức trên toàn thế giới.
');

INSERT INTO ProductDetails([Brand],[Origin],[Color],[Description]) VALUES(N'Daniel Wellington',N'Thuỵ Sĩ',N'Gorld',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
'),(N'Daniel Wellington',N'Thuỵ Sĩ',N'Sivler',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
'),(N'Daniel Wellington',N'Nhật Bản',N'Gorld',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
'),(N'Daniel Wellington',N'Nhật Bản',N'Gorld',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
'),(N'Daniel Wellington',N'Nhật Bản',N'Gorld',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
'),(N'Daniel Wellington',N'Thuỵ Sĩ',N'Gorld',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
'),(N'Daniel Wellington',N'Thuỵ Sĩ',N'Gorld',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
'),(N'Daniel Wellington',N'Thuỵ Sĩ',N'Gorld',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
'),(N'Daniel Wellington',N'Thuỵ Sĩ',N'Gorld',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
'),(N'Daniel Wellington',N'Thuỵ Sĩ',N'Sivler',N'Wanderlust sở hữu thiết kế/với điểm nhấn là mặt trước đính trái tim cùng những viên đá CZ có độ tán sắc cao kết hợp với mặt sau được khắc chữ Live – Laugh – Love mang ý nghĩa hãy sống, hãy cười và hãy cứ yêu đi vì cuộc đời luôn cho phép. Các nàng có thể xoay chuyển một cách dễ dàng tùy theo sở thích. Ngoài ra, với chất liệu bạc cao cấp, PNJSilver mang đến sản phẩm trang sức bạc vừa sở hữu độ bền lại vừa mang vẻ đẹp trẻ trung và quyến rũ.
');

INSERT INTO Categories ([Name]) VALUES(N'Thời Trang Nam'),(N'Thời Trang Nữ'),(N'Phụ kiện');
INSERT INTO TypeWires ([Name]) VALUES('No'),(N'Da'),(N'Vải'),(N'Kim loại'),(N'Nhựa'),(N'Cao su'),(N'Ceramic');
INSERT INTO Configs ([Logo],[TitleWeb],[NameShop]) VALUEs('logo.jpg',N'Watch Shop Online',N'Hommer House');
INSERT INTO Contacts ([Phone],[Address],[Email],[LinkFB]) VALUES(1268042216,N'123 Nguyễn Tri Phương, P .8 , Quận 10, TP.HCM','dangtoan030@gmail.com','fb.com/dangviettoan99');
INSERT INTO Fees ([Tax],[Transport]) VALUES(0.1,30000);
INSERT INTO Policies ([Name],[Icon]) VALUES(N'Đổi tra trong vòng 12 giờ','change.png'),(N'Đổi tra trong vòng 12 giờ','change.png'),(N'Đổi tra trong vòng 12 giờ','change.png');
INSERT INTO Users ([Username],[Password]) VALUES('admin','1234');
INSERT INTO Promotions ([Name],[FromDate],[ToDate],[Discount],[Amount]) VALUES('No','1/1/1999','1/1/1999',0,0);

INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('V_01',1000000,3,1,1),('V_01',1000000,3,1,2),('V_01',1000000,3,1,3),('V_01',1000000,3,1,4),('V_01',1000000,3,1,5),('V_01',1000000,3,1,6),('V_01',1000000,3,1,7),('V_01',1000000,3,1,8),('V_01',1000000,3,1,9),('V_01',1000000,3,1,10);
INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_01',1000000,2,4,11),('DH_04',1000000,2,2,12),('DH_04',1000000,1,7,13),('DH_01',1000000,2,3,14),('DH_01',1000000,1,3,15),('CA_02',1000000,2,3,16),('CA_02',1000000,1,7,17),('DH_01',1000000,1,6,18),('DH_04',1000000,2,4,19),('DH_04',1000000,1,3,20);
INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_01',1000000,1,2,21),('DH_01',1000000,2,4,22),('CA_02',1000000,1,6,23),('DH_01',1000000,1,4,24),('CA_02',1000000,2,4,25),('DH_04',1000000,1,6,26),('DH_04',1000000,1,5,27),('CA_02',1000000,1,3,28),('DH_04',1000000,1,7,29),('DH_04',1000000,1,3,30);
INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_04',1000000,2,2,31),('DH_04',1000000,1,2,32),('DH_04',1000000,2,6,33),('CA_02',1000000,1,2,34),('CA_02',1000000,2,5,35),('DH_04',1000000,1,6,36),('DH_01',1000000,1,2,37),('CA_02',1000000,2,7,38),('DH_04',1000000,1,3,39),('DH_04',1000000,1,3,40);
INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('CA_02',1000000,1,3,41),('CA_02',1000000,1,7,42),('DH_04',1000000,2,2,43),('DH_01',1000000,1,5,44),('CA_02',1000000,2,4,45),('DH_04',1000000,1,5,46),('DH_01',1000000,2,3,47),('DH_01',1000000,2,4,48),('CA_02',1000000,2,7,49),('DH_01',1000000,1,3,50);
INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_04',1000000,2,4,51),('DH_01',1000000,1,2,52),('DH_01',1000000,1,3,53),('DH_01',1000000,1,3,54),('DH_04',1000000,2,4,55),('DH_01',1000000,1,3,56),('DH_01',1000000,2,3,57),('CA_02',1000000,2,7,58),('DH_01',1000000,1,7,59),('CA_02',1000000,2,7,60);
INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_01',1000000,2,6,61),('CA_02',1000000,1,5,62),('CA_02',1000000,2,3,63),('CA_02',1000000,2,2,64),('DH_04',1000000,1,2,65),('DH_04',1000000,2,7,66),('CA_02',1000000,2,7,67),('DH_04',1000000,1,2,68),('DH_01',1000000,2,5,69),('DH_04',1000000,2,4,70);
INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_01',1000000,1,2,71),('DH_01',1000000,1,6,72),('CA_02',1000000,2,7,73),('DH_01',1000000,1,7,74),('DH_04',1000000,2,2,75),('DH_04',1000000,2,6,76),('DH_01',1000000,2,5,77),('CA_02',1000000,2,4,78),('DH_04',1000000,1,4,79),('CA_02',1000000,1,7,80);
INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_01',1000000,2,7,81),('DH_04',1000000,1,3,82),('DH_04',1000000,2,5,83),('DH_01',1000000,1,5,84),('DH_01',1000000,1,7,85),('DH_01',1000000,2,3,86),('CA_02',1000000,2,5,87),('DH_01',1000000,1,4,88),('DH_04',1000000,1,2,89),('DH_04',1000000,1,3,90);
INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_01',1000000,2,3,91),('DH_04',1000000,1,4,92),('CA_02',1000000,2,3,93),('DH_04',1000000,2,7,94),('DH_01',1000000,1,7,95),('CA_02',1000000,2,7,96),('CA_02',1000000,2,7,97),('DH_04',1000000,2,7,98),('CA_02',1000000,2,2,99),('DH_04',1000000,2,7,100);



INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',43),('img_watch_2.jpg',44),('img_watch_1.jpg',45),('img_watch_1.jpg',34),('img_watch_2.jpg',27),('img_watch_2.jpg',22),('img_watch_3.jpg',2),('img_watch_1.jpg',92),('img_watch_1.jpg',45),('img_watch_1.jpg',23);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',99),('img_watch_3.jpg',100),('img_watch_3.jpg',96),('img_watch_2.jpg',25),('img_watch_2.jpg',10),('img_watch_2.jpg',67),('img_watch_1.jpg',54),('img_watch_2.jpg',33),('img_watch_1.jpg',82),('img_watch_1.jpg',91);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_3.jpg',89),('img_watch_2.jpg',78),('img_watch_3.jpg',26),('img_watch_1.jpg',52),('img_watch_2.jpg',28),('img_watch_2.jpg',39),('img_watch_3.jpg',53),('img_watch_3.jpg',31),('img_watch_3.jpg',50),('img_watch_3.jpg',7);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_3.jpg',48),('img_watch_2.jpg',82),('img_watch_1.jpg',8),('img_watch_1.jpg',97),('img_watch_1.jpg',35),('img_watch_1.jpg',26),('img_watch_3.jpg',16),('img_watch_1.jpg',96),('img_watch_1.jpg',19),('img_watch_3.jpg',67);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',72),('img_watch_3.jpg',48),('img_watch_1.jpg',82),('img_watch_1.jpg',73),('img_watch_2.jpg',66),('img_watch_3.jpg',60),('img_watch_2.jpg',69),('img_watch_2.jpg',44),('img_watch_1.jpg',16),('img_watch_3.jpg',20);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_2.jpg',33),('img_watch_3.jpg',95),('img_watch_2.jpg',98),('img_watch_2.jpg',69),('img_watch_1.jpg',75),('img_watch_3.jpg',93),('img_watch_2.jpg',45),('img_watch_3.jpg',35),('img_watch_1.jpg',38),('img_watch_3.jpg',5);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_3.jpg',27),('img_watch_1.jpg',12),('img_watch_3.jpg',99),('img_watch_2.jpg',66),('img_watch_3.jpg',65),('img_watch_2.jpg',7),('img_watch_3.jpg',60),('img_watch_2.jpg',100),('img_watch_2.jpg',24),('img_watch_3.jpg',91);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',83),('img_watch_2.jpg',7),('img_watch_2.jpg',50),('img_watch_2.jpg',21),('img_watch_3.jpg',68),('img_watch_2.jpg',12),('img_watch_1.jpg',82),('img_watch_2.jpg',21),('img_watch_2.jpg',41),('img_watch_1.jpg',87);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_2.jpg',55),('img_watch_3.jpg',29),('img_watch_1.jpg',1),('img_watch_1.jpg',47),('img_watch_3.jpg',63),('img_watch_1.jpg',85),('img_watch_2.jpg',54),('img_watch_3.jpg',57),('img_watch_3.jpg',79),('img_watch_2.jpg',14);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_2.jpg',89),('img_watch_1.jpg',71),('img_watch_1.jpg',20),('img_watch_1.jpg',80),('img_watch_1.jpg',84),('img_watch_1.jpg',32),('img_watch_1.jpg',51),('img_watch_3.jpg',17),('img_watch_2.jpg',48),('img_watch_1.jpg',41);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',43),('img_watch_2.jpg',44),('img_watch_1.jpg',45),('img_watch_1.jpg',34),('img_watch_2.jpg',27),('img_watch_2.jpg',22),('img_watch_3.jpg',2),('img_watch_1.jpg',92),('img_watch_1.jpg',45),('img_watch_1.jpg',23);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',99),('img_watch_3.jpg',100),('img_watch_3.jpg',96),('img_watch_2.jpg',25),('img_watch_2.jpg',10),('img_watch_2.jpg',67),('img_watch_1.jpg',54),('img_watch_2.jpg',33),('img_watch_1.jpg',82),('img_watch_1.jpg',91);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_3.jpg',89),('img_watch_2.jpg',78),('img_watch_3.jpg',26),('img_watch_1.jpg',52),('img_watch_2.jpg',28),('img_watch_2.jpg',39),('img_watch_3.jpg',53),('img_watch_3.jpg',31),('img_watch_3.jpg',50),('img_watch_3.jpg',7);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_3.jpg',48),('img_watch_2.jpg',82),('img_watch_1.jpg',8),('img_watch_1.jpg',97),('img_watch_1.jpg',35),('img_watch_1.jpg',26),('img_watch_3.jpg',16),('img_watch_1.jpg',96),('img_watch_1.jpg',19),('img_watch_3.jpg',67);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',72),('img_watch_3.jpg',48),('img_watch_1.jpg',82),('img_watch_1.jpg',73),('img_watch_2.jpg',66),('img_watch_3.jpg',60),('img_watch_2.jpg',69),('img_watch_2.jpg',44),('img_watch_1.jpg',16),('img_watch_3.jpg',20);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_2.jpg',33),('img_watch_3.jpg',95),('img_watch_2.jpg',98),('img_watch_2.jpg',69),('img_watch_1.jpg',75),('img_watch_3.jpg',93),('img_watch_2.jpg',45),('img_watch_3.jpg',35),('img_watch_1.jpg',38),('img_watch_3.jpg',5);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_3.jpg',27),('img_watch_1.jpg',12),('img_watch_3.jpg',99),('img_watch_2.jpg',66),('img_watch_3.jpg',65),('img_watch_2.jpg',7),('img_watch_3.jpg',60),('img_watch_2.jpg',100),('img_watch_2.jpg',24),('img_watch_3.jpg',91);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',83),('img_watch_2.jpg',7),('img_watch_2.jpg',50),('img_watch_2.jpg',21),('img_watch_3.jpg',68),('img_watch_2.jpg',12),('img_watch_1.jpg',82),('img_watch_2.jpg',21),('img_watch_2.jpg',41),('img_watch_1.jpg',87);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_2.jpg',55),('img_watch_3.jpg',29),('img_watch_1.jpg',1),('img_watch_1.jpg',47),('img_watch_3.jpg',63),('img_watch_1.jpg',85),('img_watch_2.jpg',54),('img_watch_3.jpg',57),('img_watch_3.jpg',79),('img_watch_2.jpg',14);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_2.jpg',89),('img_watch_1.jpg',71),('img_watch_1.jpg',20),('img_watch_1.jpg',80),('img_watch_1.jpg',84),('img_watch_1.jpg',32),('img_watch_1.jpg',51),('img_watch_3.jpg',17),('img_watch_2.jpg',48),('img_watch_1.jpg',41);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',43),('img_watch_2.jpg',44),('img_watch_1.jpg',45),('img_watch_1.jpg',34),('img_watch_2.jpg',27),('img_watch_2.jpg',22),('img_watch_3.jpg',2),('img_watch_1.jpg',92),('img_watch_1.jpg',45),('img_watch_1.jpg',23);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',99),('img_watch_3.jpg',100),('img_watch_3.jpg',96),('img_watch_2.jpg',25),('img_watch_2.jpg',10),('img_watch_2.jpg',67),('img_watch_1.jpg',54),('img_watch_2.jpg',33),('img_watch_1.jpg',82),('img_watch_1.jpg',91);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_3.jpg',89),('img_watch_2.jpg',78),('img_watch_3.jpg',26),('img_watch_1.jpg',52),('img_watch_2.jpg',28),('img_watch_2.jpg',39),('img_watch_3.jpg',53),('img_watch_3.jpg',31),('img_watch_3.jpg',50),('img_watch_3.jpg',7);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_3.jpg',48),('img_watch_2.jpg',82),('img_watch_1.jpg',8),('img_watch_1.jpg',97),('img_watch_1.jpg',35),('img_watch_1.jpg',26),('img_watch_3.jpg',16),('img_watch_1.jpg',96),('img_watch_1.jpg',19),('img_watch_3.jpg',67);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',72),('img_watch_3.jpg',48),('img_watch_1.jpg',82),('img_watch_1.jpg',73),('img_watch_2.jpg',66),('img_watch_3.jpg',60),('img_watch_2.jpg',69),('img_watch_2.jpg',44),('img_watch_1.jpg',16),('img_watch_3.jpg',20);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_2.jpg',33),('img_watch_3.jpg',95),('img_watch_2.jpg',98),('img_watch_2.jpg',69),('img_watch_1.jpg',75),('img_watch_3.jpg',93),('img_watch_2.jpg',45),('img_watch_3.jpg',35),('img_watch_1.jpg',38),('img_watch_3.jpg',5);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_3.jpg',27),('img_watch_1.jpg',12),('img_watch_3.jpg',99),('img_watch_2.jpg',66),('img_watch_3.jpg',65),('img_watch_2.jpg',7),('img_watch_3.jpg',60),('img_watch_2.jpg',100),('img_watch_2.jpg',24),('img_watch_3.jpg',91);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_1.jpg',83),('img_watch_2.jpg',7),('img_watch_2.jpg',50),('img_watch_2.jpg',21),('img_watch_3.jpg',68),('img_watch_2.jpg',12),('img_watch_1.jpg',82),('img_watch_2.jpg',21),('img_watch_2.jpg',41),('img_watch_1.jpg',87);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_2.jpg',55),('img_watch_3.jpg',29),('img_watch_1.jpg',1),('img_watch_1.jpg',47),('img_watch_3.jpg',63),('img_watch_1.jpg',85),('img_watch_2.jpg',54),('img_watch_3.jpg',57),('img_watch_3.jpg',79),('img_watch_2.jpg',14);
INSERT INTO Images([Src],[ProductID]) VALUES('img_watch_2.jpg',89),('img_watch_1.jpg',71),('img_watch_1.jpg',20),('img_watch_1.jpg',80),('img_watch_1.jpg',84),('img_watch_1.jpg',32),('img_watch_1.jpg',51),('img_watch_3.jpg',17),('img_watch_2.jpg',48),('img_watch_1.jpg',41);


-- INSERT INTO Products([Name],[Price],[CategoryID],[ProductDetailID]) VALUES('V_01',1000000,3,1),('V_01',1000000,3,2),('V_01',1000000,3,3),('V_01',1000000,3,4),('V_01',1000000,3,5),('V_01',1000000,3,6),('V_01',1000000,3,7),('V_01',1000000,3,8),('V_01',1000000,3,9),('V_01',1000000,3,10);
-- INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_04',1000000,1,1,11),('DH_04',1000000,2,2,12),('CA_02',1000000,2,4,13),('DH_01',1000000,2,5,14),('DH_04',1000000,1,1,15),('DH_04',1000000,1,3,16),('CA_02',1000000,1,2,17),('DH_01',1000000,1,3,18),('DH_01',1000000,1,4,19),('DH_01',1000000,1,2,20);
-- INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_01',1000000,1,4,21),('CA_02',1000000,1,3,22),('DH_04',1000000,2,4,23),('DH_01',1000000,1,6,24),('CA_02',1000000,1,3,25),('CA_02',1000000,2,5,26),('DH_01',1000000,1,6,27),('DH_01',1000000,1,5,28),('CA_02',1000000,2,1,29),('DH_01',1000000,2,5,30);
-- INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_04',1000000,1,5,31),('DH_04',1000000,2,1,32),('DH_04',1000000,2,4,33),('DH_01',1000000,1,2,34),('DH_01',1000000,2,2,35),('CA_02',1000000,2,4,36),('CA_02',1000000,1,3,37),('DH_04',1000000,2,2,38),('CA_02',1000000,2,4,39),('DH_01',1000000,1,5,40);
-- INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('CA_02',1000000,2,3,41),('CA_02',1000000,1,2,42),('DH_04',1000000,1,3,43),('DH_01',1000000,2,1,44),('DH_01',1000000,2,3,45),('DH_01',1000000,2,2,46),('DH_01',1000000,1,6,47),('DH_01',1000000,1,5,48),('DH_04',1000000,2,1,49),('DH_01',1000000,2,2,50);
-- INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_01',1000000,2,1,51),('CA_02',1000000,1,6,52),('DH_04',1000000,2,4,53),('DH_04',1000000,2,4,54),('CA_02',1000000,2,3,55),('DH_01',1000000,1,2,56),('DH_04',1000000,2,3,57),('CA_02',1000000,1,2,58),('CA_02',1000000,2,2,59),('DH_04',1000000,2,1,60);
-- INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_01',1000000,2,2,61),('DH_04',1000000,2,3,62),('CA_02',1000000,2,3,63),('DH_04',1000000,2,3,64),('DH_04',1000000,2,1,65),('CA_02',1000000,1,3,66),('CA_02',1000000,1,1,67),('DH_04',1000000,2,1,68),('DH_04',1000000,1,1,69),('CA_02',1000000,1,2,70);
-- INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('CA_02',1000000,2,2,71),('CA_02',1000000,1,3,72),('DH_01',1000000,2,3,73),('DH_01',1000000,1,6,74),('DH_01',1000000,2,4,75),('DH_01',1000000,1,3,76),('CA_02',1000000,1,4,77),('DH_01',1000000,2,6,78),('DH_01',1000000,1,5,79),('DH_04',1000000,1,2,80);
-- INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_04',1000000,1,5,81),('CA_02',1000000,2,2,82),('CA_02',1000000,2,6,83),('CA_02',1000000,2,3,84),('DH_01',1000000,2,6,85),('DH_04',1000000,2,3,86),('DH_04',1000000,1,4,87),('DH_04',1000000,2,3,88),('CA_02',1000000,1,6,89),('CA_02',1000000,2,4,90);
-- INSERT INTO Products([Name],[Price],[CategoryID],[TypeWireID],[ProductDetailID]) VALUES('DH_04',1000000,2,5,91),('CA_02',1000000,1,6,92),('DH_04',1000000,1,4,93),('DH_04',1000000,1,3,94),('DH_01',1000000,1,4,95),('DH_01',1000000,2,3,96),('DH_04',1000000,1,5,97),('DH_01',1000000,2,6,98),('DH_01',1000000,1,5,99),('DH_04',1000000,1,2,100);
